import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import {
  SandpackProvider,
  SandpackPreview,
  SandpackCodeEditor,
} from "@codesandbox/sandpack-react";
import { Campaign, loadAll } from "../data";
import { CinematicPitchPlayer } from "../components/CinematicPitchPlayer";
import type { Beat } from "../components/CinematicPitchPlayer";

/* ── default prototype (baked for the EchoDesk demo) ───────── */
const DEFAULT_CODE = `export default function App() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950 text-white font-sans antialiased">
      <header className="border-b border-slate-800/60">
        <div className="max-w-5xl mx-auto px-8 py-10 flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2 mb-4">
              <span className="px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 text-[10px] font-mono border border-emerald-500/20 tracking-widest uppercase">
                ai-generated prototype
              </span>
            </div>
            <h1 className="text-4xl font-bold tracking-tight leading-tight">
              EchoDesk AI
              <span className="text-emerald-400"> × </span>
              <span className="text-slate-300">Meridian Health</span>
            </h1>
            <p className="text-lg text-slate-400 mt-3 max-w-xl leading-relaxed">
              An AI voice receptionist that answers every patient call —
              built specifically for your 4 clinics.
            </p>
          </div>
        </div>
      </header>

      <section className="max-w-5xl mx-auto px-8 py-14">
        <h2 className="text-[10px] font-mono uppercase tracking-[0.3em] text-emerald-400 mb-6">
          Why we reached out
        </h2>
        <blockquote className="border-l-2 border-emerald-500/50 pl-6 py-5 bg-slate-800/20 rounded-r-2xl">
          <p className="text-lg text-slate-200 italic leading-relaxed">
            "Average phone hold time is now over 8 minutes, driving a 22%
            call drop rate. Appointment scheduling backlog is causing no-shows."
          </p>
          <cite className="block mt-4 text-xs text-slate-500 not-italic font-mono">
            — per your careers page · meridianhealth.example/careers/fd-1
          </cite>
        </blockquote>
      </section>

      <section className="max-w-5xl mx-auto px-8 py-14">
        <h2 className="text-[10px] font-mono uppercase tracking-[0.3em] text-emerald-400 mb-6">
          What EchoDesk does for you
        </h2>
        <div className="grid grid-cols-3 gap-5">
          {[
            { icon: "📞", title: "Answers Every Call", desc: "24/7 AI receptionist handles scheduling, triage, and routing. No more 8-minute holds." },
            { icon: "⚡", title: "Zero Hold Time", desc: "Eliminates the 22% call drop rate. Patients connect instantly, every time." },
            { icon: "🏥", title: "HIPAA Compliant", desc: "Built for healthcare from day one. SOC 2 Type II certified. PHI stays encrypted." },
          ].map((c) => (
            <div key={c.title} className="bg-slate-800/30 border border-slate-700/40 rounded-2xl p-6 hover:border-emerald-500/30 transition-colors">
              <div className="text-3xl mb-4">{c.icon}</div>
              <h3 className="text-base font-semibold mb-2">{c.title}</h3>
              <p className="text-slate-400 text-sm leading-relaxed">{c.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-5xl mx-auto px-8 py-16 text-center">
        <div className="inline-block bg-gradient-to-br from-emerald-500/10 to-cyan-500/5 border border-emerald-500/20 rounded-3xl px-14 py-12">
          <h2 className="text-2xl font-bold mb-2">Ready to eliminate hold times?</h2>
          <p className="text-slate-400 mb-8">30-day pilot · 1 clinic · cancel anytime</p>
          <button className="bg-emerald-500 hover:bg-emerald-400 text-black font-bold px-10 py-4 rounded-xl text-lg transition-colors shadow-lg shadow-emerald-500/20">
            Start ₹4,999 Pilot →
          </button>
        </div>
      </section>

      <footer className="max-w-5xl mx-auto px-8 py-8 border-t border-slate-800 text-center">
        <p className="text-slate-600 text-[10px] font-mono tracking-wider">
          Prototype autonomously generated by Revenant.AI · Hermes + OpenAI + ElevenLabs
        </p>
      </footer>
    </div>
  );
}`;

const DEFAULT_BEATS: Beat[] = [
  { time: 0,  duration: 6,  spotY: 5,  callout: "This is a working prototype built autonomously for Meridian Health." },
  { time: 6,  duration: 7,  spotY: 28, callout: "We found this pain signal directly from their public careers page." },
  { time: 13, duration: 7,  spotY: 55, callout: "Three capabilities — each maps to a specific problem they posted about." },
  { time: 20, duration: 8,  spotY: 82, callout: "One click starts a paid pilot. No meetings. Razorpay handles payment." },
];

/* ── Sandpack theme matching spectral noir ─────────────────── */
const SP_THEME = {
  colors: {
    surface1: "#08090f",
    surface2: "#0c0e17",
    surface3: "#12141f",
    clickable: "#7b869c",
    base: "#e8ecf4",
    disabled: "#485064",
    hover: "#52e0c4",
    accent: "#52e0c4",
    error: "#ff5773",
    errorSurface: "#1a0a0e",
  },
  syntax: {
    plain: "#e8ecf4",
    comment: { color: "#485064", fontStyle: "italic" as const },
    keyword: "#b98cff",
    tag: "#52e0c4",
    punctuation: "#7b869c",
    definition: "#5ef2a0",
    property: "#f5a623",
    static: "#ff9ecb",
    string: "#ffd166",
  },
  font: {
    body: '"Space Grotesk", system-ui, sans-serif',
    mono: '"JetBrains Mono", monospace',
    size: "13px",
    lineHeight: "1.6",
  },
};

export function PitchPage() {
  const { companyId } = useParams<{ companyId: string }>();
  const nav = useNavigate();
  const [camp, setCamp] = useState<Campaign | null>(null);
  const [showCode, setShowCode] = useState(false);

  useEffect(() => {
    loadAll().then(({ campaigns }) => {
      setCamp(campaigns.find((c) => c.id === companyId) ?? campaigns[0] ?? null);
    });
  }, [companyId]);

  if (!camp) {
    return (
      <div className="pp-loading">
        <span className="rv-mono" style={{ color: "var(--muted)" }}>Loading target…</span>
      </div>
    );
  }

  const code = (camp as any).playbook?.files?.["App.tsx"] ?? DEFAULT_CODE;
  const audioUrl = camp.voice_memo_ref || undefined;
  const evidence = camp.lead.score?.evidence ?? [];

  return (
    <div className="pp-root">
      {/* header */}
      <header className="pp-hdr">
        <button className="pp-back rv-mono" onClick={() => nav("/")}>← War Room</button>
        <div className="pp-hdr-center">
          <h1 className="pp-company">{camp.lead.company_name}</h1>
          <span className="rv-mono pp-person">{camp.lead.person_name} · {camp.lead.person_title}</span>
        </div>
        <span className={`rv-badge ${camp.state === "won" ? "b-won" : "b-awaiting_review"}`}>
          {camp.state.replace(/_/g, " ").toUpperCase()}
        </span>
      </header>

      {/* main grid */}
      <div className="pp-grid">
        {/* left: sandpack */}
        <div className="pp-sandbox">
          <div className="pp-sandbox-top">
            <span className="rv-eyebrow">live prototype</span>
            <button className="wr-btn rv-mono" style={{ fontSize: 10 }} onClick={() => setShowCode(!showCode)}>
              {showCode ? "Hide Code" : "View Code"}
            </button>
          </div>
          <SandpackProvider
            template="react-ts"
            files={{ "/App.tsx": code }}
            theme={SP_THEME as any}
            options={{ externalResources: ["https://cdn.tailwindcss.com"] }}
          >
            {showCode ? (
              <div className="pp-sp-split">
                <SandpackCodeEditor style={{ height: "68vh" }} readOnly />
                <SandpackPreview style={{ height: "68vh" }} />
              </div>
            ) : (
              <SandpackPreview style={{ height: "72vh", borderRadius: 12 }} />
            )}
          </SandpackProvider>
        </div>

        {/* right: cinematic player + evidence */}
        <div className="pp-right">
          <CinematicPitchPlayer
            audioUrl={audioUrl}
            companyName={camp.lead.company_name}
            beats={DEFAULT_BEATS}
          />

          <div className="pp-evidence">
            <span className="rv-eyebrow">grounded evidence</span>
            {evidence.length === 0 && (
              <p className="rv-mono" style={{ color: "var(--faint)", fontSize: 11, marginTop: 8 }}>
                No evidence excerpts for this campaign.
              </p>
            )}
            {evidence.map((e, i) => (
              <div key={i} className="pp-ev-row">
                <span className="rv-mono pp-ev-src">[{e.source}]</span>
                <span className="pp-ev-text">"{e.excerpt}"</span>
              </div>
            ))}
          </div>

          <div className="pp-cost rv-mono">
            🎬 walkthrough {camp.walkthrough_url ? "✓" : "—"} ·
            🎙 voice {camp.voice_memo_ref ? "✓" : "—"} ·
            💳 pilot {camp.payment_link ? "✓" : "—"} ·
            <span style={{ color: "var(--wisp)" }}> ${camp.cost_usd.toFixed(2)} all-in</span>
          </div>
        </div>
      </div>
    </div>
  );
}
