#!/usr/bin/env python3
"""Bake a self-contained demo dataset into the console for static deploy.

Runs the pipeline offline, then emits ``console/src/demoData.ts`` with the
campaigns AND the rendered microsite HTML inlined (so the console's iframe can
use ``srcdoc`` — no separate hosting needed). This is what makes the Vercel
deploy work as a pure static site with zero backend.

    python scripts/gen_demo_data.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    # run the pipeline fresh (offline)
    from ghost.pipeline import run_seller
    from ghost.sellers import get_seller
    from ghost.ledger import ledger

    run_seller(get_seller("ring-ai"), limit=3)

    snap = json.loads((ROOT / "out" / "ledger.json").read_text())
    campaigns = snap.get("campaigns", [])

    # inline each microsite's HTML for iframe srcdoc
    for c in campaigns:
        url = c.get("microsite_url", "")
        html = ""
        if "/sites/" in url:
            rel = url.split("/sites/", 1)[1]
            f = ROOT / "out" / "sites" / rel
            if f.exists():
                html = f.read_text()
        c["microsite_html"] = html

    # synthesize a WON deal from the promoted one so the demo shows the payoff
    promoted = next((c for c in campaigns if c.get("state") == "awaiting_review"), None)
    if promoted:
        won = json.loads(json.dumps(promoted))
        won["id"] = won["id"] + "_won"
        won["state"] = "won"
        won["lead"]["company_name"] = "Northgate Family Care"
        won["lead"]["person_name"] = "Dr. Alan Osei"
        won["email_subject"] = won["email_subject"].replace(
            promoted["lead"]["company_name"], "Northgate Family Care"
        )
        campaigns.insert(0, won)

    ts = (
        "// AUTO-GENERATED by scripts/gen_demo_data.py — do not edit by hand.\n"
        "// A self-contained demo dataset so the deployed console needs no backend.\n"
        "import type { Campaign } from './data';\n\n"
        f"export const DEMO_CAMPAIGNS: Campaign[] = {json.dumps(campaigns, indent=2)};\n"
    )
    out = ROOT / "console" / "src" / "demoData.ts"
    out.write_text(ts)
    print(f"wrote {out} ({len(campaigns)} campaigns, "
          f"{sum(1 for c in campaigns if c.get('microsite_html'))} with inlined sites)")


if __name__ == "__main__":
    main()
